### ISSUE TITLE
Show js client side console errors in logs

### ISSUE THREAD

**Issue by kellyselden** [CrowdStrike/faltest#16]
We should also try to log any ajax errors too.

**Comment by vitch** [comment]
I would suggest maybe taking it a step further.

We could gather information about all ajax requests and the status codes returned and output this at the end of every test run. This would make comparing the API interactions of a green test run against a red test run very quick and easy. And should help to very quickly narrow down failures which are happening because of broken APIs...

**Comment by kellyselden** [comment]
ajax requests will be a bit more difficult requiring a proxy https://stackoverflow.com/questions/36203022/configure-webdriverio-with-browsermobproxy.

**Comment by kellyselden** [comment]
Tracked here https://github.com/CrowdStrike/faltest/issues/317
